const ProjectList = [
  {
    id: 1,
    // src: "./assets/techspace.png",
    src: "./assets/techspace-img.png",
    altTag: "laptop open to blogsite",
    name: "techspace",
    details: "CMS technology blogging site",
    specs: "FULLSTACK: SERN | Handlebars | JavaScript | Bcrypt",
    deployedUrl: "https://radiant-plains-16714.herokuapp.com/",
    githubRepo: "https://github.com/AmyWilford/Tech-Space---CMS-Blog",
  },
  {
    id: 2,
    src: "./assets/budget-img.png",
    altTag: "budget paperwork",
    name: "Budget",
    details: "Budgeting site designed for non-financially minded budgeters",
    specs: "FULLSTACK: SERN | Handlebars | JavaScript | Bcrypt",
    deployedUrl: "https://bloodcurdling-vampire-96793.herokuapp.com/",
    githubRepo:
      "https://github.com/AmyWilford/Budgethttps://github.com/AmyWilford/Budget",
  },
  {
    id: 3,
    src: "./assets/weather-img.png",
    altTag: "weather dashboard",
    name: "Weather Dashboard",
    details: "Get up to date weather forecasts wherever your plans take you",
    specs: "FRONTEND: JavaScript | JQuery | 3rdParty API ",
    deployedUrl: "https://amywilford.github.io/Weather-Dashboard/",
    githubRepo: "https://github.com/AmyWilford/Weather-Dashboard",
  },
  {
    id: 4,
    src: "./assets/wordplay-img.png",
    altTag: "dictionary entry",
    name: "Wordplay",
    details: "A word game that tests your knowledge, not your luck",
    specs: "FRONTEND: JavaScript | JQuery | 3rdParty API ",
    deployedUrl: "https://amywilford.github.io/Word-Play/",
    githubRepo: "https://github.com/AmyWilford/Word-Play",
  },
  {
    id: 5,
    src: "./assets/pokedex-img.png",
    altTag: "Pokeball",
    name: "Mistys Pokedex",
    details: "An online Pokémon encyclopaedia",
    specs: "FRONTEND: React | Axios | JavaScript | 3rdParty API",
    deployedUrl: "https://amywilford.github.io/Mistys-Pokedex/",
    githubRepo: "https://github.com/AmyWilford/Mistys-Pokedex",
  },
  {
    id: 7,
    src: "./assets/javascript.png",
    altTag: "coffee mug",
    name: "Javascript",
    specs: "FULLSTACK: MERN | GraphQL | Stripe | JWT | JavaScript",
    details: "An ecommerce store specializing in personalized mugs",
    deployedUrl: "https://whispering-inlet-47426.herokuapp.com/",
    githubRepo: "https://github.com/AmyWilford/Mug-Store",
  },
];

export default ProjectList;
